name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # 리포지토리를 체크아웃합니다.

      - name: Set up GCC
        run: sudo apt-get install -y g++
        # GCC를 설치합니다.

      - name: Compile project
        run: make
        # 프로젝트를 컴파일합니다.

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: path/to/build/artifacts
        # 빌드 아티팩트를 업로드합니다.

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # 리포지토리를 체크아웃합니다.

      - name: Compile project
        run: make
        # 프로젝트를 컴파일합니다.

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: path/to/build/artifacts
        # 빌드 아티팩트를 업로드합니다.

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # 리포지토리를 체크아웃합니다.

      - name: Set up MSYS2
        run: |
          choco install -y msys2
          refreshenv
          C:\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm"
          C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc"
        # MSYS2를 설치하고 필요한 패키지를 설치합니다.

      - name: Add MSYS2 to PATH
        shell: bash
        run: echo '::add-path::/c/msys64/mingw64/bin' >> $GITHUB_ENV
        # MSYS2를 PATH에 추가합니다.

      - name: Build with Makefile
        run: make
        # Makefile을 사용하여 빌드합니다.

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: path/to/build/artifacts
        # 빌드 아티팩트를 업로드합니다.
